apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
      - name: myapp
        image: registry.digitalocean.com/andeeapp:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000